### ISSUE TITLE
support h264 for older IOS devices and OSX safari via config avconv params

### ISSUE THREAD

**Issue by djay** [collective/wildcard.media#16]
This answer shows how to convert a video to be the most compatible. 

- Only use the H.264 Baseline Profile Level 3.0
- Resolution below 640 x 480 and framerate up to 30 fps
- B frames are not supported in the Baseline profile.
- bitrate limit of 900kb.

http://stackoverflow.com/questions/4240915/h-264-encoded-mp4-presented-in-html5-plays-on-safari-but-not-ios-devices

The current code assumes an uploaded mp4 is already compatible so doesn't convert it.

**Comment by djay** [comment]
I think I'll just put in a site setting of avconv params per output type.

**Comment by djay** [comment]
@seanupton I think your approach looks interesting but perhaps over complex?
What I will do is build on top of https://github.com/collective/wildcard.media/commit/5c4a665e78b71acc52694dc8ee2a7c2763643b7f
to have avconv params per output format. (but not based on size or input format) as this is simpler.
@vangheem can you not make a release until this is done so that we don't have to worry about upgrades to the registry?
I think being able to set this globally for all sites on an instance would be useful but I would tend to use either environment vars or zope.conf for this. That means no additional python packages need to be deployed. Maybe if there are no registry entries, then it would look for the environment var PLONE_AVCONVPARAMS_MP4 etc?

**Comment by vangheem** [comment]
@djay no problem about not doing a release, just let me know when.
