### ISSUE TITLE
Convert process parameters

### ISSUE THREAD

**Issue by displacedaussie** [collective/wildcard.media#21]
On the latest version of Ubuntu, the available version of libav-tools includes a version of the 'aac' encoder that is "experimental". The default convert process triggered by wildcard.media fails with the following error:

    $ avconv -i test.mp4 testoutput.mp4
    ....
    encoder 'aac' is experimental and might produce bad results.
    Add '-strict experimental' if you want to use it.

It would be useful if we could configure extra parameters via the control panel to pass to the convert command.

    $ avconv -i test.mp4 -strict experimental testoutput.mp4

**Comment by vangheem** [comment]
We could add a control panel option for this. Also, might be useful to include some info about this in the README. Would you mind making a pull request?

**Comment by displacedaussie** [comment]
Pull request is here: https://github.com/collective/wildcard.media/pull/22

**Comment by vangheem** [comment]
Thanks!
