### ISSUE TITLE
Plone 5 status?

### ISSUE THREAD

**Issue by neilferreira** [collective/wildcard.media#25]
Hi all

I've managed to install this addon on a Plone 5 installation without any issues using the master branch of this project.

Adding audio and videos are both working fine, adding youtube video links however is not.

I get the following 404 in my browser, and a blank window as seen in this screenshot.  Is anyone still actively working on getting a stable version of this project for Plone 5.0 ?

Over the next few days I will likely be looking to resolve some of the issues related to Plone 5.0 to get this addon up and running on a site.

GET http://0.0.0.0:8081/Sandbox/test-test/++resource++wildcard-media/components/mediaelement/build/flashmediaelement.swf 404 (Not Found)

![screenshot from 2015-11-10 16 20 14](https://cloud.githubusercontent.com/assets/1369584/11057549/fedb1512-87c6-11e5-9f88-70e433248334.png)

**Comment by cekk** [comment]
Looks like that the _flashmediaelement.swf_ file is missing in the build folder: https://github.com/collective/wildcard.media/tree/master/wildcard/media/browser/static/components/mediaelement/build

I have the same issue, but i don't know how to fix that.

**Comment by vangheem** [comment]
Add the file?

**Comment by senner** [comment]
I just pushed an update for bower.json, to link to chosen old repo.. .and updated mediaelement to latest 2.18 .  As well fixed a .gitignore that ignored the build/ folder.. Please check it out and test ...

**Comment by vangheem** [comment]
New version out: https://pypi.python.org/pypi/wildcard.media/2.0.1
