### ISSUE TITLE
When rendering a video from a youtube url (without youtube upload enabled) the video elements double up

### ISSUE THREAD

**Issue by neilferreira** [collective/wildcard.media#26]
https://github.com/collective/wildcard.media/blob/master/wildcard/media/browser/templates/video_macro.pt#L41

On this line you can see that if you've specified a youtube URL you will get a <video> element that links to that youtube url.  The <video> element above will also be output but not contain any video, it is missing a tal:condition="not: video/youtube_url"

I'll try get a PR in for this.

**Comment by cekk** [comment]
@neilferreira this should be fixed with pr #28 and already merged.
@vangheem i think that we can close this issue

**Comment by neilferreira** [comment]
Looks good!
