### ISSUE TITLE
Youtube video: use iframe instead video tag?

### ISSUE THREAD

**Issue by cekk** [collective/wildcard.media#29]
hi, what do you think about using the iframe instead of video tag in the youtube video section in the template?

With my Android device (Nexus 5) i can't send the video on fullscreen (the link in the player doesn't work).
With the iframe, works pretty good, and it should automatically detect the browser and show a video tag or show an alternative (i think the flash player).

Of course i need to add a simple parser for the url, to compose the correct one.
We already made it for redturtle.video: https://github.com/RedTurtle/collective.rtvideo.youtube/blob/master/collective/rtvideo/youtube/browser/videoembedcode.py#L168

If is ok for you, i can create a PR for this.

**Comment by vangheem** [comment]
Yup, iframe is better.

**Comment by cekk** [comment]
Resolved with PR #36
