### ISSUE TITLE
Is Plone 4.3 still supported?

### ISSUE THREAD

**Issue by ale-rt** [collective/wildcard.media#30]
Installing on a Vanilla Plone wildcard.media >= 2.0.0 I get this javascript errror:

 - Uncaught ReferenceError: define is not defined

The error is related to this instruction
 - https://github.com/collective/wildcard.media/blob/4ae8b4cd56f7952c05d26b7263d4ea9aaf5ff8fd/wildcard/media/browser/static/integration.js#L5774

**Comment by vangheem** [comment]
In deed, I broke Plone 4 compatibility. Please try https://pypi.python.org/pypi/wildcard.media/2.0.2 and see how that works for you. Thanks for checking.

**Comment by ale-rt** [comment]
Yeah! It works great :)
Thanks a lot!
