### ISSUE TITLE
Broken reference widget on Plone 5 with wildcard.media

### ISSUE THREAD

**Issue by cekk** [collective/wildcard.media#42]
Steps to reproduce the error:
- a clean Plone 5.0.2 site
- install wildcard.media
- edit a content, and the reference widget is broken like in this screenshot:
![schermata 2016-02-17 alle 17 04 16](https://cloud.githubusercontent.com/assets/1402078/13115560/8a75425e-d598-11e5-87a2-8842446a8a75.png)

The strange thing is that i don't have any js error on console, other browsers doesn't have problems, and other widgets (the keywords widgets for example) works fine. 

Any ideas?

**Comment by vangheem** [comment]
This is a wildcard.media specific issue? This doesn't happen with other content?

**Comment by cekk** [comment]
I don't know..this happens to all reference widgets on the site, so in every content type.
Could it be a problem with its registered resources? Some kind of conflict with mockup?

**Comment by vangheem** [comment]
but only when you install wildcard.media?

**Comment by vangheem** [comment]
I can not reproduce with 5.0.2 and wildcard.media. Maybe it's something else going on?

**Comment by cekk** [comment]
Ops..i forgot to mention that i have this issue only on Firefox (on osx)..and only when i install wildcard.media :(
To reproduce it, i used buildout.coredev and added wildcard.media in development mode.

**Comment by vangheem** [comment]
Cool. Thanks, I can reproduce it now. I'll dig into it.

**Comment by cekk** [comment]
super fast..thanks!

**Comment by cekk** [comment]
For the future: do you understand why this breaks only on firefox?

**Comment by vangheem** [comment]
I do not right now unfortunately and didn't have time to dig into it.

That pattern was getting initialized twice which shouldn't happen.
