### ISSUE TITLE
error: Not a recognized archive type: /opt/plone4/buildout-cache/downloads/dist/wildcard.media-2.0.3.zip

### ISSUE THREAD

**Issue by merpdotcom** [collective/wildcard.media#44]
Is this something with my system, or a bug?
Buildout has been working fine for other add-ons.
Plone 4.3.11.
Ubuntu 16.04 LTS
Please advise.
Thanks!

**Comment by merpdotcom** [comment]
root@cms:/opt/plone4/buildout-cache/eggs# cp ../downloads/dist/wildcard.media-2.0.3.zip ./
root@cms:/opt/plone4/buildout-cache/eggs# unzip wildcard.media-2.0.3.zip 
Archive:  wildcard.media-2.0.3.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of wildcard.media-2.0.3.zip or
        wildcard.media-2.0.3.zip.zip, and cannot find wildcard.media-2.0.3.zip.ZIP, period.

**Comment by merpdotcom** [comment]
Maybe, for some reason buildout didn't download the file completely?
I went ahead and deleted the .zip from downloads/dist and eggs. And re-ran buildout.
Appears to have solved it. Sorry for bothering.
Cheers!

**Comment by vangheem** [comment]
delete the downloads/dist/wildcard.media-2.0.3.zip and try running buildout again.

Looks like something interrupted your download.

**Comment by merpdotcom** [comment]
Yep, that did the trick. Cheers!
