### ISSUE TITLE
Where i can find tutorial or example on how to use wildcard.media plugin for plone?

### ISSUE THREAD

**Issue by ivanNextG** [collective/wildcard.media#53]
Hi guys, i am new to plone and i need to use wildcard.media but i don't have clue how to install or use it. I have google it but unable to find any example, how to, or tutorial. so, if you can point me to the right direction, i will very appreciate it...

Thank you so much for your help

**Comment by flipmcf** [comment]
All add-ons (should) follow the same procedure to install, and it's pretty well documented here: https://docs.plone.org/manage/installing/installing_addons.html

find your buildout.cfg and add this package's name to 'eggs':

    [buildout]
    ...
    eggs =
        ...
        Products.PloneFormGen
        collective.supercool
        wildcard.media

then, re-run your buildout

`bin/buildout`

and restart your plone instance.

Lastly, visit 'add-ons' under site setup and install it.

hope this helps (and we can close the ticket)

**Comment by flipmcf** [comment]
https://community.plone.org/t/wildcard-media-examples/6950

The github issue tracker is for bugs and features of the package.  There is demo talk about this package on the plone community site.  https://community.plone.org/t/wildcard-media-examples/6950
