### ISSUE TITLE
Conversion utilities avprobe and avconv do not ship with newer distros

### ISSUE THREAD

**Issue by pigeonflight** [collective/wildcard.media#60]
wildcard.media depends on avprobe and avconv to perform conversions. Newer distros, for example Ubuntu 18.04 no longer ships with avprobe and avconv.

We need to consider having the `convert.py` utility support other alternative utilities for conversion.

**Comment by pigeonflight** [comment]
Apparently `ffmpeg` and `ffprobe` can act as drop in replacements for `avconv` and `avprobe`.
On Ubuntu 18.04, I was able to create symlinks like this:
```
ln -s /usr/bin/ffmpeg /usr/bin/avconv
ln -s /usr/bin/ffprobe /usr/bin/avprobe
```

**Comment by senner** [comment]
They are the same thing. Depends on the perspective of the product, and support group.
